#!/usr/bin/env python3
"""Package the checked JSON for a static page, using Python's standard library."""
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
source = ROOT / 'data' / 'data.json'
destination = ROOT / 'data.js'
data = json.loads(source.read_text(encoding='utf-8'))
assert len(data['models']) == 6
assert sum(len(model['control']) + sum(len(guide) for guides in model['genes'].values()
                                    for guide in guides)
           for model in data['models']) == 126
payload = json.dumps(data, ensure_ascii=False, allow_nan=False, separators=(',', ':'))
destination.write_text(
    '// Generated by scripts/build_browser_data.py from checked publication source data.\n'
    'window.UNIVERSITY_LAB_DEMO_DATA = ' + payload + ';\n', encoding='utf-8',
)
print('Built data.js: 6 models, 126 reported measurements.')
